services:
  - type: web
    name: planb-backend
    env: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: planb-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: "*"
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_PUBLIC_KEY
        generateValue: true

databases:
  - name: planb-db
    databaseName: planb
    user: planb_user
    plan: free
